### ISSUE TITLE
Unable to resolve module RCTDeviceEventEmitter

### ISSUE THREAD

**Issue by saidimu** [walmartreact/react-native-orientation-listener#1]
On Android, [this line](https://github.com/walmartreact/react-native-orientation-listener/blob/master/index.js#L4) causes that error.

**Comment by kenwheeler** [comment]
Shouldn't that just resolve?

**Comment by saidimu** [comment]
It should but for some reason it doesn't on a vanilla react-native install on Android (on a Ubuntu Linux dev box, I should add). Same applies to other utilities under `react-native/Libraries/`. It may be that `react-native init` does some extra setup for iOS.

**Comment by saidimu** [comment]
Here's the react-native issue on this error: https://github.com/facebook/react-native/issues/3080

**Comment by bartonhammond** [comment]
Same problem but with ios.

**Comment by Mokto** [comment]
+1 on ios

**Comment by atticoos** [comment]
+1 on ios,  `react-native@0.15.0`

**Comment by jimthedev** [comment]
I am still getting this on iOS. I am on react native 0.19

**Comment by calvinf** [comment]
When will the npm version of this module be updated?  This bug fix has happened, but the module hasn't been published with a new version containing this fix.

**Comment by calvinf** [comment]
@jimthedev as a short-term fix, you can install the version of the npm module currently available in the github repo which doesn't have the problem:

> npm install walmartreact/react-native-orientation-listener --save

**Comment by jimthedev** [comment]
I'm using another method, thanks.
