### ISSUE TITLE
Inconsistent callback parameters between Android and iOS

### ISSUE THREAD

**Issue by atticoos** [walmartreact/react-native-orientation-listener#10]
`getOrientation` invokes a callback with **two parameters**, `orientation` and `device`, but Android invokes a callback with **one parameter**, a map containing `orientation` and `device`. 

These should really be consistent, otherwise we're dealing with two separate implementations to achieve the same goal

**Comment by kenwheeler** [comment]
Noted, I'll get this in for the next version
