### ISSUE TITLE
[Android] Possible bug: wrong orientation being sent 

### ISSUE THREAD

**Issue by aoriani** [walmartreact/react-native-orientation-listener#12]
``` java
@Override
      public void onOrientationChanged(int orientation) {
        WritableNativeMap params = new WritableNativeMap();
        String orientationValue = "";
        if(orientation == 0) {
          orientationValue = "PORTRAIT";
        } else {
          orientationValue = "LANDSCAPE";
...
```

The [doc](http://developer.android.com/reference/android/view/OrientationEventListener.html#onOrientationChanged%28int%29) for `onOrientationChanged` says : 

> Called when the orientation of the device has changed. orientation parameter is in degrees, ranging from 0 to 359. orientation **is 0** degrees when the device is oriented in its **natural** position, (...)

Natural position is portrait for phones and 7" tablets, but landscape for 10" tablets. See http://android-developers.blogspot.com/2010/09/one-screen-turn-deserves-another.html. You may have to resort to screen dimensions again.

**Comment by jerson** [comment]
same error 👍
