### ISSUE TITLE
[Android] No events for POTRAIT

### ISSUE THREAD

**Issue by satya164** [walmartreact/react-native-orientation-listener#3]
Most of the times, no event fires when orientation is changed to potrait. But tons of events are fired when orientation changes to landscape.

**Comment by kenwheeler** [comment]
what are the conditions under which this occurs?

**Comment by satya164** [comment]
@kenwheeler I just tried on my Android phone. Normal conditions.

**Comment by pyromaticx** [comment]
Having the same issue. Running on a Samsung S4 phone. If held flat in portrait mode will fire a few `LANDSCAPE` events, then if tilted upwards 45deg fires many more `LANDSCAPE` events. `PORTRAIT` seems to fire once then immediately `LANDSCAPE` again several dozen times. 

React Native 0.21

**Comment by pyromaticx** [comment]
For anyone working on this, a decent workaround is to use the event as a trigger and use `Orientation.getOrientation` and check for a difference in state. 

my implementation:

```
  componentDidMount() {
    Orientation.addListener(() => {this.getOrientation()});
  }
  getOrientation() {
    Orientation.getOrientation(
      (orientation) => {
        if(orientation.orientation !== this.state.orientation) {
          this.setState({
            orientation: orientation.orientation
          });
        }
      });
  }
```

This will reduce the number of setState calls and work around the false `LANDSCAPE` value, as `getOrientation` will return the correct value.
Once #10 is resolved `orientation.orientation` will just be `orientation` hopefully?

**Comment by jatazoulja** [comment]
This is caused by: `if(orientation == 0)`
doing a Log.i on orientation it seldom goes to 0, always goes around 357~359 or -1 (which is intermittent.) but 0 will likely hit 1:100.
Testing this on actual device, the emulator doesn't seem to have this behaviour.
