### ISSUE TITLE
RCTDeviceEventEmitter.removeListener is not a function

### ISSUE THREAD

**Issue by bartgryszko** [walmartreact/react-native-orientation-listener#6]
Error shows up when trying to remove listener with `Orientation.removeListener(this._setOrientation);` what make sense as there is no `removeListener` method in RN [EventEmitter.js](https://github.com/facebook/react-native/blob/master/Libraries/vendor/emitter/EventEmitter.js)

**Comment by kenwheeler** [comment]
great catch.

**Comment by bartgryszko** [comment]
I've resolved it with:

```
componentDidMount(){
  this.orientationListener = Orientation.addListener(this._setOrientation);
}

componentWillUnmount() {
  this.orientationListener.remove();
}
```

Check if that make sense to you.
