### ISSUE TITLE
Crashes if initialized too early

### ISSUE THREAD

**Issue by atticoos** [walmartreact/react-native-orientation-listener#8]
I attach a listener when my root component mounts, which appears to be too early in the lifecycle; before the catalyst is ready (specifically [here](https://github.com/walmartreact/react-native-orientation-listener/blob/master/android/src/main/java/com/walmartreact/ReactOrientationListener/ReactOrientationListenerModule.java#L45))

```
E/AndroidRuntime(32754): java.lang.RuntimeException: Trying to invoke JS before CatalystInstance has been set!
E/AndroidRuntime(32754):    at com.facebook.react.bridge.ReactContext.getJSModule(ReactContext.java:94)
E/AndroidRuntime(32754):    at com.walmartreact.ReactOrientationListener.ReactOrientationListenerModule$1.onOrientationChanged(ReactOrientationListenerModule.java:45)
E/AndroidRuntime(32754):    at android.view.OrientationEventListener$SensorEventListenerImpl.onSensorChanged(OrientationEventListener.java:143)
E/AndroidRuntime(32754):    at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:405)
E/AndroidRuntime(32754):    at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(32754):    at android.os.MessageQueue.next(MessageQueue.java:143)
E/AndroidRuntime(32754):    at android.os.Looper.loop(Looper.java:122)
E/AndroidRuntime(32754):    at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime(32754):    at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(32754):    at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(32754):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime(32754):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
W/ActivityManager(  541):   Force finishing activity 1 com.robinpowered.rooms/com.robinrooms.MainActivity
```

If there's a way to queue items for the catalyst, that would be safer

**Comment by jwo** [comment]
@ajwhite I ran into the exact same problem, so I'll comment and listen here. In order to move forward, I hacked this up. It sleeps and then sends the event (which gets the JSModule which by then has activated). Note that I'm not a fan of this, but if people need to move forward, this does work:

```
try {
  Thread.sleep(100);  
    nfc.sendEvent("NFCFOUND", null); // The thing that eventually tries to send a message to React
} catch(InterruptedException ex) {
  Thread.currentThread().interrupt();
}
```

**Comment by kenwheeler** [comment]
Whats the long term fix on this

**Comment by atticoos** [comment]
Avoid accessing the Catalyst before it's available. You can check if the `reactApplicationContext` [hasActiveCatalystInstance](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/bridge/ReactContext.java#L113-L115) as well as hook into the lifecycle events with [addLifecycleEventListener](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/bridge/ReactContext.java#L117-L119) which _may_ let you observe _when_ the catalyst becomes available, and _then_ take attach the listener.
